//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginOdev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int PageId { get; set; }
        public string PageContent { get; set; }
        public string PageUrl { get; set; }
        public string PageTitle { get; set; }
    }
}
